[package]
name = "tesys_derive"
version = "0.1.0"
authors = ["Sam Morrell <samuelmorrell@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.15.4"
quote = "0.6.8"
lazy_static = "1.1.0"
colored = "1.6.1"
proc-macro2 = "0.4.24"
